# Site settings
title: Jekyll
email: juanmahvelez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description. Modify this in the _config.yml
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juanmahvelez.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  juanmahvelez

# Build settings
markdown: kramdown
